version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - kubik-net

  kubik-backend:
    build: .
    container_name: kubik-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    networks:
      - kubik-net

volumes:
  redis-data:

networks:
  kubik-net: