version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - kubik-net

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: password123
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - kubik-net

  # minio-init:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   networks:
  #     - kubik-net
  #   entrypoint: >
  #     /bin/sh -c "
  #       sleep 5;
  #       mc alias set local http://minio:9000 admin password123 &&
  #       mc mb -p local/my-dev-bucket || true &&
  #       mc anonymous set download local/my-dev-bucket
  #     "

  kubik-backend:
    build: .
    container_name: kubik-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      # - minio
      # - minio-init
    networks:
      - kubik-net

volumes:
  redis-data:
  # minio-data:

networks:
  kubik-net:
