version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - kubik-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: kubik_db
      POSTGRES_USER: kubik_user
      POSTGRES_PASSWORD: kubik_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kubik-net

  kubik-backend:
    build: .
    container_name: kubik-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
      - postgres
    networks:
      - kubik-net

volumes:
  redis-data:
  postgres-data:

networks:
  kubik-net: