name: Build & Deploy to Server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy Project to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: '.'
          target: '~/app'

      - name: SSH and Deploy with Docker Compose (only backend)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app

            # Copy .env dari home ke project
            cp ~/.env .env

            # Stop & remove kubik-backend saja
            docker compose down kubik-backend || true
            docker compose rm -f kubik-backend || true

            # Rebuild dan jalankan hanya backend (Redis & MinIO tetap jalan)
            docker compose up -d --build kubik-backend