name: Deploy POS BE

on:
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: pos-backend
  STACK_NAME: pos
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          RAW_VERSION=${GITHUB_REF#refs/tags/}
          VERSION=$(echo "$RAW_VERSION" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]//g')
          IMAGE=$REGISTRY/$REPO_OWNER/pos-be

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            docker login $REGISTRY -u ${{ github.actor }} --password ${{ secrets.GHCR_TOKEN }}
            docker service update --image $IMAGE:$VERSION --with-registry-auth $STACK_NAME_$APP_NAME
