name: Build & Deploy to Server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: '.'
          target: '~/app'

      - name: SSH and Deploy on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo ">> Check folder deploy/development"
            ls -lah ~/app/deploy/development || echo

            echo ">> Check disk space"
            df -h

            echo ">> Stop and erase container redis-server if exist"
            docker stop redis-server 2>/dev/null || true
            docker rm redis-server 2>/dev/null || true

            echo ">> Create docker network kubik-net if not exist"
            docker network inspect kubik-net >/dev/null 2>&1 || docker network create kubik-net

            echo ">> Run Redis with docker compose"
            docker compose -f ~/app/deploy/development/docker-compose.yml up -d redis

            echo ">> Build Docker image kubik-backend"
            cd ~/app
            docker build -t kubik-backend .

            echo ">> Stop and erase container kubik-backend if exist"
            docker stop kubik-backend 2>/dev/null || true
            docker rm kubik-backend 2>/dev/null || true

            echo ">> Run container kubik-backend"
            docker run -d --name kubik-backend --network kubik-net --restart always -p 8080:8080 kubik-backend
