name: Build & Deploy to Server

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: '.'
          target: '~/app'

      - name: SSH and Build Docker on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo ">> Copying .env if exists"
            cp ~/.env ~/app/.env || true

            echo ">> Navigating to app directory"
            cd ~/app

            echo ">> Creating Docker network if not exists"
            docker network inspect kubik-net >/dev/null 2>&1 || docker network create kubik-net

            echo ">> Stopping and removing existing redis-server if exists"
            docker rm -f redis-server || true

            echo ">> Starting redis with docker compose"
            docker compose -f deploy/development/docker-compose.yml up -d redis

            echo ">> Building backend Docker image"
            docker build -t kubik-backend .

            echo ">> Stopping and removing old container"
            docker stop kubik-backend || true
            docker rm kubik-backend || true

            echo ">> Running new container"
            docker run -d --name kubik-backend --network kubik-net --restart always -p 8080:8080 kubik-backend
