name: Deploy POS BE

on:
  push:
    tags:
      - 'v*.*.*' # contoh v1.0.0

env:
  APP_NAME: pos-backend
  STACK_NAME: pos
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository_owner }}/pos-be

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

      - name: SSH to server and update service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GHCR_TOKEN }}
            docker service update --image $IMAGE:${VERSION} --with-registry-auth $STACK_NAME_$APP_NAME
